export const USER_KEY = 'user';
export const MEALS_TOKEN_KEY = 'mealsToken';
export const DRINKS_TOKEN_KEY = 'drinksToken';
export const MAX_RECOM_VALUE = 6;
export const LINK_COPIED_TIME = 3000;
export const MEALS_RECIPES = 'https://www.themealdb.com/api/json/v1/1/search.php?s=';
export const DRINK_RECIPES = 'https://www.thecocktaildb.com/api/json/v1/1/search.php?s=';
export const MEALS_CATEGORY = 'https://www.themealdb.com/api/json/v1/1/list.php?c=list';
export const DRINK_CATEGORY = 'https://www.thecocktaildb.com/api/json/v1/1/list.php?c=list';
